### ISSUE TITLE
Create doc about the release process

### ISSUE THREAD

**Issue by alouvion-aneo** [aneoconsulting/armonik#1004]
todo in this doc :
- [x] dire l'ensemble des repo a release, dans quel ordre, les csproj a updater, les lignes de commandes pour updater (tools)
- [ ] Comment faire un patch
  - [ ] Armonik.Api
  - [ ] ArmoniK.Core
  - [ ] ArmoniK.Extensions.Csharp
  - [x] ArmoniK.Samples
  - [ ] ArmoniK.Admin.GUI
  - [x] ArmoniK
- [ ] Comment faire une release
  - [ ] Armonik.Api
  - [ ] ArmoniK.Core
  - [ ] ArmoniK.Extensions.Csharp
  - [ ] ArmoniK.Samples
  - [ ] ArmoniK.Admin.GUI
  - [ ] ArmoniK
- [ ] comment faire les release notes, comment faire le mail de communication et a qui
idem pour les patch à partir de quoi on part cf le tag précédent etc

# Table of contents
- [Repo Dependencies](#Repo_dependencies)
- [Armonik full Release process](#Release_process)
- [Armonik patches](#Patch_process)

# Repo dependencies : <a name="Repo_dependencies"></a>
```mermaid
graph TD;
  Armonik.Api(Armonik.Api);
  ArmoniK.Core(ArmoniK.Core);
  ArmoniK.Extensions.Csharp(ArmoniK.Extensions.Csharp);
  ArmoniK.Samples(ArmoniK.Samples);
  ArmoniK.Admin.GUI(ArmoniK.Admin.GUI)
  ArmoniK(ArmoniK);
  Armonik.Api-->|need previous step output|ArmoniK.Core-->|need previous step output|ArmoniK;
  Armonik.Api-->|need previous step output|ArmoniK.Extensions.Csharp-->|need previous step output|ArmoniK.Samples-->ArmoniK;
  ArmoniK.Extensions.Csharp-->|need previous step output|ArmoniK;
  Armonik.Api-->|need previous step output|ArmoniK.Admin.GUI-->ArmoniK;
```

```mermaid
graph TD;
    Armonik.Api-->ArmoniK.Core-->ArmoniK;
    Armonik.Api-->ArmoniK.Extensions.Csharp-->ArmoniK.Samples-->|weak dependency|ArmoniK;
    Armonik.Api-->ArmoniK.Admin.GUI-->ArmoniK;
    if(If I patch this)-->then(I need to wait for previous step before to be released);
    if2(If I patch this)-->|weak dependency|then2(I don't need to wait for previous step before to be released);

```
So, it means if you patch or release `ArmoniK.Extensions.Csharp` you also have to do it for `ArmoniK.Samples` and `ArmoniK`
<a name="Release_process"></a>
 <details>
  <summary><h2>I - Release process :</h2></summary>
 <details open>
  <summary><h3>A-Armonik.Api release :</h3></summary>
If a new version of **Armonik.Api** need to be released, go to : https://github.com/aneoconsulting/ArmoniK.Api/releases/new
Fill combo : `choose a tag` with the new tag version
Click `Generate Release Notes`
Update the generated release notes if needed
Click `Publish Release`
</details>

 <details open>
  <summary><h3>B-Armonik.Core release :</h3></summary>
As you can see in the dependency graph, if you want to deliver a new Armonik.Api version you also need to updates references to api

step 1
If you need to update api nuggets :
```bash
export your_name=al
export api_nugget_tag_before=3.6.0
export api_nugget_tag_before_after=3.7.0
export branch_name="$your_name/upgrade_core_from_${api_nugget_tag_before}_to_${api_nugget_tag_before_after}"
export core_tag_to_be_patched=main
export your_armonik_core_folder=./
cd $your_armonik_core_folder
to be tested : git pull origin master --rebase -b "$branch_name"
todo : add gitclone syntax for fresh folder
git grep -l "$api_nugget_tag_before" -- *.csproj | xargs sed -i "/Armonik.Api/s/$api_nugget_tag_before/$api_nugget_tag_before_after/"
git commit -a -m "APIs nuggets updated from ${api_nugget_tag_before} to ${api_nugget_tag_before_after}"
```
step 2 
If a new version of **Armonik.Core** need to be released, go to : https://github.com/aneoconsulting/ArmoniK.Core/releases/new
Fill combo : `choose a tag` with the new tag version
Click `Generate Release Notes`
Update the generated release notes if needed
Click `Publish Release`
</details>

 <details open>
  <summary><h3>C-ArmoniK.Extensions.Csharp release :</h3></summary>

```bash
todo
```
</details>

 <details open>
  <summary><h3>D-ArmoniK.Samples release :</h3></summary>

```bash
todo
```
</details>
 <details open>
  <summary><h3>E-ArmoniK.Admin.GUI release :</h3></summary>

```bash
todo
```
</details>
 <details open>
  <summary><h3> F-Armonik release :</h3></summary>

```bash
todo
```
</details>
</details>
<a name="Patch_process"></a>
 <details>
  <summary><h2>II - Patch process : </h2></summary>
 <details open>
  <summary><h3>A-Armonik.Api patch :</h3></summary>

```bash
todo
```
</details>
 <details open>
  <summary><h3>B-Armonik.Core patch :</h3></summary>

```bash
todo
```
</details>
 <details open>
  <summary><h3>C-ArmoniK.Extensions.Csharp patch :</h3></summary>

```bash
todo
```
</details>
 <details open>
  <summary><h3>D-ArmoniK.Samples patch :</h3></summary>

```bash
export your_name=al
export ext_csharp_nugget_tag_samples_before=0.9.2
export ext_csharp_nugget_tag_samples_after=0.9.4
export branch_name="$your_name/upgrade_ext.csharp_from_${ext_csharp_nugget_tag_samples_before}_to_${ext_csharp_nugget_tag_samples_after}"
export sample_tag_to_be_patched=v2.12.0
export your_armonik_sample_folder=./
cd $your_armonik_sample_folder
git checkout tags/$sample_tag_to_be_patched -b "$branch_name"
git grep -l "$ext_csharp_nugget_tag_samples_before" -- *.csproj | xargs sed -i "/Armonik.Dev/s/$ext_csharp_nugget_tag_samples_before/$ext_csharp_nugget_tag_samples_after/"
git commit -a -m "ext CSharp nuggets updated from ${ext_csharp_nugget_tag_samples_before} to ${ext_csharp_nugget_tag_samples_after}"
```
create new release from github : https://github.com/aneoconsulting/ArmoniK.Samples/releases/new
</details>

 <details open>
  <summary><h3>E-ArmoniK.Admin.GUI patch :</h3></summary>

```bash
todo
```
</details>
 <details open>
  <summary><h3>F-Armonik patch</h3></summary>

#### 1-Get Armonik Repo :
```bash
#infra tags :
export tag_infra_before=2.12.0  #update it with your own version without v
export tag_infra_after=2.12.1  #update it with your own version without v

#branch name :
export your_name=al
export branch_name="$your_name/patch_from_v${tag_infra_before}_to_v${tag_infra_after}"

#if you don't already have a branch create one:
cd your_working_folder
git clone https://github.com/aneoconsulting/ArmoniK.git
cd Armonik
# get the last patch version and create a local branch from it
git checkout tags/v$tag_infra_before -b $branch_name

#To be tested : seems detached If I do this in one command : 
git clone --branch v$tag_infra_before https://github.com/aneoconsulting/ArmoniK.git
```

### 2-if you need to include `Armonik.Core` patch
```bash
#core tags :
export tag_core_before=0.12.2 #update it with your own version
export tag_core_after=0.12.3 #update it with your own version
git grep -l "$tag_core_before" -- *.txt | xargs sed -i "/core/s/$tag_core_before/$tag_core_after/"
git grep -l "$tag_core_before" -- *.tfvars | xargs sed -i "/tag/s/$tag_core_before/$tag_core_after/"
git grep -l "$tag_core_before" -- *.json | xargs sed -i "/core/s/$tag_core_before/$tag_core_after/"
git commit -a -m "core updated from $tag_core_before to $tag_core_after"
```

### 3-if you need to include `ArmoniK.Extensions.Csharp` patch
```bash
#extension c# tags :
export tag_ext_before=0.9.2 #update it with your own version
export tag_ext_after=0.9.4 #update it with your own version
git grep -l "$tag_ext_before" -- *.txt | xargs sed -i "/worker/s/$tag_ext_before/$tag_ext_after/"
git grep -l "$tag_ext_before" -- *.tfvars | xargs sed -i "/tag/s/$tag_ext_before/$tag_ext_after/"
git grep -l "$tag_ext_before" -- *.json | xargs sed -i "/extcsharp/s/$tag_ext_before/$tag_ext_after/"
git commit -a -m "extension c# updated from $tag_ext_before to $tag_ext_after"
```

### 4-If you need to include `Armonik.Samples` patch
```
export tag_samples_before=2.12.0 #update it with your own version without v
export tag_samples_after=2.12.1 #update it with your own version without v
git grep -l "v$tag_samples_before" -- *.txt | xargs sed -i "/samples/s/v$tag_samples_before/v$tag_samples_after/"
git grep -l "$tag_samples_before" -- *.json | xargs sed -i "/samples/s/$tag_samples_before/$tag_samples_after/"
git commit -a -m "samples updated from $tag_samples_before to $tag_samples_after"
```

### 5-If you need to include `ArmoniK.Api` patch
```bash
Todo
```

### 6-Then now you can update update `ArmoniK`
```bash
git grep -l "$tag_infra_before" -- *.json | xargs sed -i "/infra/s/$tag_infra_before/$tag_infra_after/"
git commit -a -m "infra updated from $tag_infra_before to $tag_infra_after"
```

### 7-update infra Changelogs
```bash
# you need to change it manualy
**We have to define what we want here :
- changes from all other repos ?
- changes only from ArmoniK ?
- change generated by github when we create release ?
- ....... If yes we need to push branch a first time to have access to github release process**
git commit -a -m "infra changelogs updated"
```
TODO : git push command + create PR from your tag branch to main

### 8-if review ok => create tag release
go to : https://github.com/aneoconsulting/ArmoniK/releases/new
in choose a tag write : v$tag_infra_after  (ex: v2.12.1 here we need v)
in target, choose your branch : $branch_name (ex: myname/patch_...)
click generate release note
=> add informations you have added in changelogs (no need for new version title it will be added by git)
check if it is looking good in https://github.com/aneoconsulting/ArmoniK/releases
go back to your pr
if you have this message : This branch is out-of-date with the base branch
*Important* => update with merge commit
why ? because we don't want new main dev integrated inside our tag
merge or squash merge PR to main
</details>
</details>

 <details>
<summary><h2>III - Release communication</h2></summary>
TODO :
- Template of Email : 
- Version numbers
- Important features
- All changes
- Breaking changes
- ...

</details>

**Comment by esoubiran-aneo** [comment]
C'est quoi la différence entre old factories et new factories ? @alouvion-aneo

**Comment by alouvion-aneo** [comment]
> C'est quoi la différence entre old factories et new factories ? @alouvion-aneo

c'est pour dire qu'il y a une diff de la façon de faire une release ou de patcher.
avec la refacto on peut créer le tag à partir de la gui de git. (cf la démo de vend dernier)
avant il fallait pousser dans la branche release.
Ce commentaire va bientôt disparaitre de la doc.
Mais par exemple Damien qui doit patcher dans en 10.x ext c# (old factory) du coup il n'a pas la même process

**Comment by esoubiran-aneo** [comment]
> > C'est quoi la différence entre old factories et new factories ? @alouvion-aneo
> 
> c'est pour dire qu'il y a une diff de la façon de faire une release ou de patcher. avec la refacto on peut créer le tag à partir de la gui de git. (cf la démo de vend dernier) avant il fallait pousser dans la branche release. Ce commentaire va bientôt disparaitre de la doc. Mais par exemple Damien qui doit patcher dans en 10.x ext c# (old factory) du coup il n'a pas la même process

Okk, je vois.

Je pense que ça serait vraiment intéressant d'avoir un exemple real-world sur ce titre : if review ok => create tag release. ça permettrait de mieux comprendre le process de release !
