### ISSUE TITLE
Add multiple control plan

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#106]
* Expected v2.8
* Min replicas 3
* Metrics: CPU>=80%, Mem>=80% 

PS: The HPA for control plane is done in dev branch [LZK/hpa-control-plane](https://github.com/aneoconsulting/ArmoniK/tree/LZK/hpa-control-plane), which can be merged with [main](https://github.com/aneoconsulting/ArmoniK/tree/main).

**Comment by lzianekhodja** [comment]
Mettre en place un HPA pour control plane ?
Si oui, en se basant sur quelle(s) métrique(s)?

**Comment by lemaitre-aneo** [comment]
Pas forcémment un HPA, mais au moins 3 instances pour la haute dispo.

**Comment by wkirschenmann** [comment]
Je dirais un HPA avec un min = 3 et un max tel que cpu < 80% et mem < 80%

Wil

**Comment by lzianekhodja** [comment]
D'acc, donc :
* Min replicas 3
* Metrics: CPU < 80% && Mem  80%
