### ISSUE TITLE
Redis timeout not expected

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#111]
It has been noticed that some runs are failing with an error related to the REDIS  as seen in the screenshot:

![3](https://user-images.githubusercontent.com/85945328/162731276-a1f7a09d-4443-4196-b0ed-ff5b83113f0d.png)

This error occurs on:
* Localhost
* Raspberry cluster
* AWS infra

There are no very test case known who can reproduce systematically the error.

Investigations:
* Redis timeout (Not really the problem)
* Can be TLS but not sure if it is the only problem. Ttry TLS 1.2 (on raspberry pi  server)

**Comment by lzianekhodja** [comment]
This error occurs on:
* Localhost
* Raspberry cluster
* AWS infra

**Comment by ngruelaneo** [comment]
Not reproductible and seems to have diseapear. It could have happen because of the polling agent.
