### ISSUE TITLE
Show custom text in GUI

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK#1148]
Hello,

As a user, I want to be able to show in my GUI the environment I'm. In fact, end user could deploy a test, a pre-prod and a prod environment. I also want to expose my custom version because I built a custom ArmoniK for my usage.

The test environment can be used to try to do some crazy thing that you don't to be done in a prod.

To alert the end user where he is, we could expose, through an API, some custom data. In the GUI, we could use these data to show a banner with a label and the selected color.

## Proposal

The API will return an object with 3 keys:

```json
{
	"label": "string",
	"version": "string",
	"color": "string"
}
```

These values are injected through environment variables in the control plane and return using the ArmoniK.Api.

Here the normalized environment variables that we must document:

```txt
ARMONIK_ENVIRONMENT_LABEL=<value>
ARMONIK_ENVIRONMENT_VERSION=<value>
ARMONIK_ENVIRONMENT_COLOR=<value>
```

Then, the GUI can fetch it and show it in the GUI.

In the `infrastructure/quick-deploy/localhost`, I want to be able to update them using the `parameters.tfvars` file.

## Why not use env vars in the GUI containers

This could not be achieved through the GUI container since the application is fully rendered in our CI and in the client browser. Furthermore, if someone wants to use this value for their own GUI or CLI, using an API is way more logical since everything is in the API since the beginning.

@aneojgurhem @dbrasseur-aneo @lemaitre-aneo and @lzianekhodja, what do you think of this solution?

**Comment by dbrasseur-aneo** [comment]
Isn't it a bit redundant with the fact we can get the version of the different components ?

**Comment by esoubiran-aneo** [comment]
> Isn't it a bit redundant with the fact we can get the version of the different components ?

These variables can be set by user of ArmoniK. They can put whatever they want. On the other side, versions returned by current API are versions from our components. It can't be change by user.

**Comment by esoubiran-aneo** [comment]
We could achieve this using API or using the Ingress.

**Comment by lemaitre-aneo** [comment]
I think the best it to use the ingress. I will try to implement something today.

**Comment by esoubiran-aneo** [comment]
> I think the best it to use the ingress. I will try to implement something today.

Nice, thanks!
