### ISSUE TITLE
Use Api v3.x in Extensions.CSharp

### ISSUE THREAD

**Issue by ddubuc** [aneoconsulting/ArmoniK#117]
With the addition of a server in agent to receive request from worker instead of usinf bidirectionnal streams, we need to update the part that was simplifying the use of stream.
This part will be moved in ArmoniK.Api. Therefore, the package should be used to access it.
PR : https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/pull/58

**Comment by dbrasseur-aneo** [comment]
PR : https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/pull/58
