### ISSUE TITLE
Discussion about possible optimisation

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#128]
- [ ] push dependencies (instead of pull)
- [ ] tree-based reduction to resolve dependencies when task has a large number of dependencies
- [ ] push status
- [ ] push cancellation
- [ ] heart-beat using keep-alive (either TCP or Grpc)
- [ ] communication/computing overlap in pollingAgent

**Comment by wkirschenmann** [comment]
push dependencies (instead of pull) => needs a proper discussion and to get measurements.
Performance impact of dependencies pulling depends on whether the dependencies are already finished upon first dependency check. We need to observe what happens on real situation.

**Comment by wkirschenmann** [comment]
tree-based reduction to resolve dependencies when task has a large number of dependencies => yes !

**Comment by wkirschenmann** [comment]
heart-beat using keep-alive (either TCP or Grpc) => Yes !
Probably the first item to implement since it is not very complex and will have a huge impact. It will allow to use batch operation in the DB.
