### ISSUE TITLE
Possible performance degradation

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#129]
Run time for 10'000 tasks on 10 cores

| Run id | time |
|--------|------|
| 1 | 60.84361 |
| 2 | 95.60299 |
| 3 | 128.4761 |
| 4 | 154.0599 |
| 5 | 181.0816 |
| 6 | 202.8386 |
| 7 | 221.6747 |

ArmoniK: commit 785a35ff2424fc4c89c6e1200e79ab69d9453909
ArmoniK.Core: commit 75c52b94db5d886b593ac50fd1fd22c10ba17049 + Hashed index

**Comment by lemaitre-aneo** [comment]
Time seems to be almost linear. It might be missing a compound index

**Comment by ngruelaneo** [comment]
Not seen anymore with snapshot version 0.5.6
