### ISSUE TITLE
Integrate AMQP 

### ISSUE THREAD

**Issue by wkirschenmann** [aneoconsulting/ArmoniK#13]
During the refresh, a Queue system based on MongoDB has been implemented because it was easier to integrate in early stages. Other queues implementation need to be provided. AMQP is one of them to support Active MQ.

**Comment by ddubuc** [comment]
@aneojgurhem is working on the web console activation. Following messages activities

**Comment by ddubuc** [comment]
Review AMQP for AWS Cloud
