### ISSUE TITLE
Integrate Amazon MQ

### ISSUE THREAD

**Issue by wkirschenmann** [aneoconsulting/ArmoniK#14]
During the refresh, a Queue system based on MongoDB has been implemented because it was easier to integrate in early stages. Other queues implementation need to be provided. AWS SQS is one of them

**Comment by ddubuc** [comment]
Will be replace by Amazon MQ

**Comment by ddubuc** [comment]
Working. Need to manage user & password https://github.com/aneoconsulting/ArmoniK/issues/69
