### ISSUE TITLE
No service for type has been registered

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#161]
**Describe the bug**

Polling agent is in unhealthy state with error: No service for type 'ArmoniK.Core.Common.Stream.Worker.WorkerStreamHandler' has been registered.

**To Reproduce**

1. Deploy ArmoniK with Core tag 0.5.8-SNAPSHOT.38.62cec65 and Worker tag 0.5.3

**Expected behavior**
ArmoniK should be deployed

**Screenshots**

![1](https://user-images.githubusercontent.com/85945328/167011040-ed9f28ff-6bf8-434c-b98b-2a98a3a41713.png)

**Infra**
- Target : Localhost
- Infra Version : 72f41cd5aa8e702667c856d10c066975510dd1ef
- Core Images and Version (if known) : 0.5.8-SNAPSHOT.38.62cec65
- Worker Image and Version (if known) : 0.5.3

**Additional context**

**Comment by aneojgurhem** [comment]
Fixed by https://github.com/aneoconsulting/ArmoniK.Core/pull/51
