### ISSUE TITLE
Investigate GetTaskStatus exception when task id does not exist

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#167]
Need more informations to investigate:

* Expected behavior
* Observed behavior
* Steps to reproduce the problem

**Comment by aneojgurhem** [comment]
This PR ( https://github.com/aneoconsulting/ArmoniK.Core/pull/70 ) add an async test that shows that a TaskNotFoundException in code should return a rpc exception with NotFound as status code.
Whithout more details on the errors, versions and how to reproduce, we cannot go further @ddubuc.
