### ISSUE TITLE
Error on the WaitForAvailability for large subtasking computation

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#168]
**Describe the bug**
Error on the WaitForAvailability when we execute a large subtasking computation.

**To Reproduce**
1. Launch the subtasking test of the Symphony like program: sum(x^2)
2. Use à large a list of numbers: range(1, 5000)
3. The program:

![program](https://user-images.githubusercontent.com/85945328/168231132-3ee1a170-5ffa-433a-9e9f-dc863bbcfb0f.png)

**Expected behavior**
Compute (1^2 + 2^2 + 3^2 + ... + 5000^2)

**Screenshots**
Client:

![client](https://user-images.githubusercontent.com/85945328/168231351-0cf80d0d-ad8e-40d2-85ce-9188c2393375.png)

Submitter:

![submitter](https://user-images.githubusercontent.com/85945328/168231389-45fbdca2-51a4-4a47-a595-3212f770b727.png)

Polling agent:

![polling-agent](https://user-images.githubusercontent.com/85945328/168231466-0d3d9d3e-3ded-4388-92b6-d3b4ed4c4d6d.png)

![polling-agent2](https://user-images.githubusercontent.com/85945328/168231511-8aee90ff-e609-4dae-bc1a-be4d5c76ca3f.png)

Context arround the error:

![context](https://user-images.githubusercontent.com/85945328/168231568-3fc277cd-8951-4832-8f7a-61f5348c2a4f.png)

**Infra**
- Target : Localhost
- Queue (Activemq managed or not) : not managed ActiveMQ
- DataBase: not managed MongoDB
- Cache : not managed Redis
- Infra Version : v2.7.0
- Core Images and Version: 0.5.8
- Worker Image and Version: 0.5.6
- Samples version: 2.7.0

**Additional context**
The error can occur with a list of 100 numbers too.

**Comment by lemaitre-aneo** [comment]
Fixed in core 0.5.10
