### ISSUE TITLE
MongoDBWaitQueueFullException : The wait queue for acquiring a connection is full

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#170]
**Describe the bug**
HTCMock crashes for 1000 tasks and 1 level when there is NOT READY compute plane.

**To Reproduce**
1. Deploy ArmoniK with min replica count = 1 or 0
2. Launch HTCMock with 1000 tasks and 1 level
3. The command is:
docker run --rm -e Grpc__Endpoint="${Grpc__Endpoint}" -e HtcMock__NTasks=1000 -e HtcMock__TotalCalculationTime="00:00:00.100" -e HtcMock__DataSize="1" -e HtcMock__MemorySize="1" -e HtcMock__SubTasksLevels=1 dockerhubaneo/armonik_core_htcmock_test_client:0.5.10

**Expected behavior**
Compute 1000 tasks with 1 level

**Screenshots**

![pollster](https://user-images.githubusercontent.com/85945328/168237732-c887f339-67f7-4dfb-bd5a-96614b53937c.png)

![task](https://user-images.githubusercontent.com/85945328/168237763-d999827c-2fdf-4c8b-a1cd-af3278a40e73.png)

![process](https://user-images.githubusercontent.com/85945328/168237778-fab4ef65-5206-4199-a625-729e4b8a77bd.png)

**Infra**
- Target : localhost
- Queue: not managed ActiveMQ
- DataBase : not managed MongoDB
- Cache : not managed Redis
- Infra Version : v2.7.2
- Core Images and Version : 0.5.10
- Worker Image and Version : 0.5.10
- Worker image : dockerhubaneo/armonik_core_htcmock_test_client

**Additional context**
The test is successful when there is at leat two compute planes.

**Comment by lemaitre-aneo** [comment]
Fixed in 0.5.12
