### ISSUE TITLE
Cannot process tasks with large payload when using ingress

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#183]
**Describe the bug**

Tasks using large payload fail to be processed when the endpoint of control plane is given by ingress.

**To Reproduce**

1. Deploy ArmoniK with ingress and tls/mtls set to false
2. Launch test core stream

**Expected behavior**

Pass all tests of core stream

**Screenshots**
![1](https://user-images.githubusercontent.com/85945328/168982322-be2e38ce-63b2-45c7-a5d1-5c15d641912d.png)

![2](https://user-images.githubusercontent.com/85945328/168982334-5742aac8-b338-48ca-a07a-088cb1a2e179.png)

![3](https://user-images.githubusercontent.com/85945328/168982344-00d60ff2-cee4-4f84-aa69-075006c9e474.png)

![4](https://user-images.githubusercontent.com/85945328/168982359-1188153b-9f46-49ef-acf9-c56f73541cb3.png)

![5](https://user-images.githubusercontent.com/85945328/168982373-359341a1-1ecb-4ed1-8d92-3ea538a57c90.png)

![6](https://user-images.githubusercontent.com/85945328/168982386-d269b7c7-93b9-4b07-806a-a55aef868338.png)

**Infra**

- Target : Localhost
- Queue : not managed ActiveMQ
- DataBase : not managed MongoDB
- Cache : not managed Redis
- Infra Version : v2.7.1
- Core Images and Version (if known) : 0.5.9
- Worker Image and Version (if known) : 0.5.7

**Additional context**

The test is successful without ingress

**Comment by lemaitre-aneo** [comment]
notepad for future work:
- https://stackoverflow.com/questions/67430437/grpc-send-timeout-doesnt-work-nginx-closes-grpc-streams-unexpectedly
- https://stackoverflow.com/questions/65881809/concurrent-requests-through-nginxs-grpc-pass-failed
