### ISSUE TITLE
feat(gui-dashboard-ui): create application cards ui

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK#195]
aneoconsulting/ArmoniK.Admin.GUI#35

**Comment by esoubiran-aneo** [comment]
ArmoniK.Admin.GUI#3

**Comment by esoubiran-aneo** [comment]
aneoconsulting/ArmoniK.Admin.GUI#4

**Comment by esoubiran-aneo** [comment]
@ddubuc ça te va ?

![image](https://user-images.githubusercontent.com/103997512/169517035-31d69cdf-3ec2-4482-882d-4484a9ac0813.png)

**Comment by ddubuc** [comment]
Je les aurais plus mis en dessous et en alignement horizontal sans forcément indiqué Tasks in ****
ca fait gagné de la place par carte

**Comment by esoubiran-aneo** [comment]
![image](https://user-images.githubusercontent.com/103997512/169541921-567d625a-a110-4bbe-9297-be5875a30b7b.png)

et lorsque l'utilisateur passe sa souris sur l'une des valeurs (ou ronds), il a plus d'informations !

**Comment by esoubiran-aneo** [comment]
merged, can be closed
