### ISSUE TITLE
Integrate with REDIS

### ISSUE THREAD

**Issue by wkirschenmann** [aneoconsulting/ArmoniK#20]
During the technical refresh, MongoDB has been used to emulate an object storage to allow for an easier integration. Other longterm solutions need to be integrated. Redis is one of them.

**Comment by wkirschenmann** [comment]
Integration will be done using the IDistributedCache interface from Microsoft : https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-6.0

The bridge to use this interface is already available.

**Comment by ddubuc** [comment]
Need to review the redis configuration 
Create external Redis
Need to develop source code to store client payload into Redis

**Comment by wkirschenmann** [comment]
3. is already implemented. RedisDistributedCache is injected as a IObjectStorage
