### ISSUE TITLE
Proto : updates

### ISSUE THREAD

**Issue by aneojgurhem** [aneoconsulting/ArmoniK#205]
- [X] Remove small tasks from worker proto
- [x] ~~Clarify the result reply in worker (remove last key ? batch ?)~~
- [x] Add a process request to acknowledge result reception and send an error if there is an issue with result sending from the worker
- [X] Remove kill sub tasks parameter at the worker level since we launch subtasks only when the parent task is completed ==> deprecated for now
- [x] ~~Remove WaitForCompletion since we use data driven model~~
- [x] Make sure that task id, session id and result id are generated by core instead of given by the user
- [x] ~~Partitions and partitioning service~~
- [x] #439
- [x] Remove status failed

A solution to simplify the worker proto is to split the bidirectional stream into several unidirectional streams (Polling Agent becomes a gRPC server): WIP #335 

https://developers.google.com/protocol-buffers/docs/style

**Comment by ngruelaneo** [comment]
link with: https://github.com/aneoconsulting/ArmoniK/issues/333
