### ISSUE TITLE
No logs in Seq on some Linux VMs for localhost deployment

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#257]
* No logs in Seq on some Linux VMs for localhost deployment (Red Hat Entreprise Linux 8, NixOs)
* Check cloudwatch on AWS

**Comment by lemaitre-aneo** [comment]
This is a problem with the docker logging driver. It should be set to `json-file` for fluent-bit to work.
https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver
https://rancher.com/docs/rancher/v2.0-v2.4/en/cluster-admin/tools/cluster-logging/

https://github.com/aneoconsulting/ArmoniK/pull/258
