### ISSUE TITLE
Add random failures to htcmock

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK#267]
**Describe the solution you'd like**
It would be nice to have (configurable) random failures in htcmock in order to test cluster failures. The randomness should most likely be deterministic.

**Describe alternatives you've considered**
We could manually trigger a pod failure using `kubectl`, but this is not suited for automated tests.

**Comment by aneojgurhem** [comment]
PR : https://github.com/aneoconsulting/ArmoniK.Core/pull/80
