### ISSUE TITLE
Update to new Task Output in extensions.csharp

### ISSUE THREAD

**Issue by aneojgurhem** [aneoconsulting/ArmoniK#276]
```mermaid
graph TD
    Task[Task Ends] --> Error{Return Output}
    Error -->|OK| Completed[Task Completed]
    Error -->|KO| Failed
    Error -->|Throw Grpc Error| grpcex{retry < MaxRetries}
    grpcex -->|Yes| SubmitDuplicate[Task Error + Submit task duplicate]
    grpcex -->|No| Failed[Task Error + No retries]
```

- Child tasks are only submitted when the parent task completes successfully
- Task Completed
  - Status Ok
  - Subtask creation OK
  - Outputs OK
  - subtasks are created when received (with creating status i.e; created "on the fly") and submitted at the end of the parent task
- Task Error
  - Cancellation of outputs and subtasks
  - Error not managed by application (raise a gRPC Error that will be transfered to the polling agent), annulate output subtasks.
  - create Task Duplicate (with link for monitoring and number of retry) and transfer output creation responsibility
- Task resubmission
  - copy of task metadata with retry number as postfix

**Comment by ddubuc** [comment]
Don't know what I have to do. Could please point on change I have to do ?
