### ISSUE TITLE
PollsterError : "Error with messageHandler null"

### ISSUE THREAD

**Issue by ddubuc** [aneoconsulting/ArmoniK#300]
**Describe the bug**
In version Armonik.Core 0.5.14-SNAPSHOT.48.17c30c4
When we execute 100 000 tasks with the batch method SubtmitTask and wait after the GetDataStatus method. There is severak error in pollster.cs "Error with messageHandler null"

**To Reproduce**
1. Submit 10 000 tasks and 100 000 tasks 
2. Try to getDataStatus of results
3. See error in Seq 

**Expected behavior**
This exception is slowing down the process

**Screenshots**
![image](https://user-images.githubusercontent.com/5215353/175832776-0cb16924-1692-461f-befd-e64cc698c2b6.png)

**Infra**
- Target WSL, Last Armonik Infra on main
- Core Images and Version (if known) :
 https://github.com/aneoconsulting/ArmoniK.Core/actions/runs/2549228457      ->  0.5.14-SNAPSHOT.48.17c30c4
- Worker Image and Version (if known) : 0.6.1

**Comment by ngruelaneo** [comment]
Link to https://github.com/aneoconsulting/ArmoniK/issues/266 (TBC)
