### ISSUE TITLE
Split bidirectionnal stream between worker and agent

### ISSUE THREAD

**Issue by aneojgurhem** [aneoconsulting/ArmoniK#335]
Split bidirectionnal stream between worker and agent in order to simplify the management of the different requests from the worker in the agent. It will also allow to have a better management of errors in requests.

- [x] one server running all the time that only accepts requests when a task is executed
- [x] ~~communication token to help debug mismatches between tasks sending requests and server receiving them~~
- [x] need to create proper services for agent server
- [x] properly finalize task creation
- [x] ~~re-add tests for request processor~~
- [x] ~~re-add tests for Stream taskhandler (in ArmoniK.Api ?)~~
- [x] doc

**Comment by lemaitre-aneo** [comment]
> * communication token to help debug mismatches between tasks sending requests and server receiving them

Maybe we could have multiple servers, each dedicated to a single task at a given moment, with a round robin allocation. We could have idle servers in order to detect some client misuses.

**Comment by lemaitre-aneo** [comment]
Tests in another ticket: #341 #342
