### ISSUE TITLE
DocFX does not properly render mermaid

### ISSUE THREAD

**Issue by jfonseca-aneo** [aneoconsulting/ArmoniK#340]
See for example https://aneoconsulting.github.io/ArmoniK.Core/articles/tasks.html and compare [to its source markdown](https://github.com/aneoconsulting/ArmoniK.Core/blob/master/Documentation/articles/tasks.md/#L1)

**Comment by ngruelaneo** [comment]
See issue docFX: https://github.com/dotnet/docfx/issues/2292
