### ISSUE TITLE
Reinsert SubmitTask for UnifiedApi

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK#344]

**Comment by alouvion-aneo** [comment]
goal : 
Add possibility to submit task from worker pod/zip(unified API)
Add possibility to submit task with dependencies from worker pod/zip(unified API)
Add EndToEndTest with subtasking (similar to CheckSubtaskingTree_SymphonySDK.SubtaskingTreeClient)
