### ISSUE TITLE
Proto for GUI admin

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#358]
Write a proposition for grpc proto which will implement the current GUI admin api 

- [x] Create a service for sessions https://github.com/aneoconsulting/ArmoniK.Api/pull/15
- [x] ~~Create a service for applications https://github.com/aneoconsulting/ArmoniK.Api/pull/22~~
- [x] Create a service for tasks https://github.com/aneoconsulting/ArmoniK.Api/pull/24

**Comment by esoubiran-aneo** [comment]
- [ ] Create a service for sessions
- [ ] Create a service for applications
- [ ] Create a service for tasks

**Comment by esoubiran-aneo** [comment]
- [Tasks](https://github.com/aneoconsulting/ArmoniK.Api/pull/24)
- [Applications](https://github.com/aneoconsulting/ArmoniK.Api/pull/22)
