### ISSUE TITLE
Add debug symbols in dotnet 6 projects in Core

### ISSUE THREAD

**Issue by aneojgurhem** [aneoconsulting/ArmoniK#361]
As debug symbols does not impact dotnet 6 performances, we can provide them in projects.

```
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
    <DebugType>Embedded</DebugType>
  </PropertyGroup>
```

**Comment by wkirschenmann** [comment]
Optimize can also be done for debug project. Hence, I'd unify that and provide these options in the global PropertyGroup.

From: aneojgurhem ***@***.***>
Sent: Thursday, July 21, 2022 19:39
To: aneoconsulting/ArmoniK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aneoconsulting/ArmoniK] Add debug symbols in dotnet 6 projects in Core (Issue #361)


As debug symbols does not impact dotnet 6 performances, we can provide them in projects.

  <PropertyGroup Condition="'$(Configuration)'=='Release'">

    <Optimize>true</Optimize>

    <DebugType>Embedded</DebugType>

  </PropertyGroup>

-
