### ISSUE TITLE
Missing support for 'application/grpc-web-text'

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK#366]
In order to be able to communicate from the app to the control plane without using the api, I use a grpc communication. But Seq return this error `Request content-type of 'application/grpc-web-text' is not supported.`

[A solution seems to be describe here!](https://stackoverflow.com/questions/65136901/asp-net-application-grpc-web-is-not-supported)

**Comment by aneojgurhem** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-6.0

**Comment by esoubiran-aneo** [comment]
Working on it here: https://github.com/aneoconsulting/ArmoniK.Core/tree/jg/grpcweb
