### ISSUE TITLE
Find and fix CreateLargeTasksAuthShouldMatch failing only in pipeline when authorization is disabled 

### ISSUE THREAD

**Issue by dbrasseur-aneo** [aneoconsulting/ArmoniK#405]
The CreateLargeTasksAuthShouldMatch test in Common/tests/Auth/AuthenticationIntegrationTest.cs of Core is failing only in pipeline.
I was unable to find the issue as it works without issue both in windows and wsl.
It fails by raising a RPCException without a cause, leading to a "Status OK".
On the db/authorization branch, only the NoImpersonateNoAuthorization test cases fail.
On the main branch, only some of the NoAuthorization test cases fail.

Both cases fail when authorization is disabled, but maybe another branch would fail on another case.
The test is ignored at the moment

**Comment by ngruelaneo** [comment]
Verify if there are not one or more `using` of disposable object missing.

**Comment by dbrasseur-aneo** [comment]
After investigation, it looks like a race condition between tests. The refactor seems to have fixed the issue
