### ISSUE TITLE
Session is recreated at each OnInvoke (SendTask) call

### ISSUE THREAD

**Issue by arnaudcacib** [aneoconsulting/ArmoniK#50]
Hello j’ai repéré un bug au niveau des sessions. Dans le code actuel d’un SendTasks à l’autre on perd la session
(version 2.1.0 image dockerhubaneo/armonik_worker_dll:0.0.4)
Pour reproduire avec le sample :
 add comment at begining of OnSessionEnter and OnInvoke on server side.
you get something like that in logs :

08 Jan 2022 21:10:46.860 OnInvoke session count=1
08 Jan 2022 21:10:46.859 OnSessionEnter count=1
08 Jan 2022 21:10:46.766 OnInvoke session count=1
08 Jan 2022 21:10:46.765 OnSessionEnter count=1
08 Jan 2022 21:10:46.662 OnInvoke session count=1
08 Jan 2022 21:10:46.661 OnSessionEnter count=1 (celui là et les suivants c’est un bug)
08 Jan 2022 21:10:46.566 OnInvoke session count=1
08 Jan 2022 21:10:46.565 OnSessionEnter count=1 (celui là est ok c’est le premier)

On voit que le on sessionEnter est appelé à chaque fois
En effet dans le code GRPC l’instance est stateless du coup on perd les variables d’un appel à l’autre
J’ai fixé de mon coté en modifiant avec le code en jaune suivant :

dans le computerService.cs
proposition de correctif : cridWorker_ + SessionId en static pour garder les variables du précédent run 
Au final ça donne qqch comme ça dans les logs après le fix
08 Jan 2022 21:10:46.860 OnInvoke session count=1
08 Jan 2022 21:10:46.766 OnInvoke session count=1
08 Jan 2022 21:10:46.662 OnInvoke session count=1
08 Jan 2022 21:10:46.566 OnInvoke session count=1
08 Jan 2022 21:10:46.565 OnSessionEnter count=1 (celui là est ok c’est le premier)

Si vous pouvez corriger ça dans votre prochaine version  ça me serait pratique.
Thx
Arnaud

**Comment by aneojgurhem** [comment]
Salut Arnaud,
Tu utilises combien de pods pour le le compute plane ?
Jérôme

**Comment by arnaudcacib** [comment]
salut peut importe. je fais des tests entre 1 et 4. Damien est sur le sujet. il me dit qu'il reproduit

**Comment by aneojgurhem** [comment]
Non justement, si tu utilises plusieurs pod, il faut que tu initialises ta session dans chaque pod.
Dans ce cas, c'est normal que tu aies ce log plusieurs fois.
Jérôme

**Comment by ddubuc** [comment]
Fixed issue #50 with SessionContext. New Armonik's version 2.1.1 available 17/01/2022
