### ISSUE TITLE
When local WSL restarted, the fact that its ip address changed cause the Armonik's compute plane calculate throw exception

### ISSUE THREAD

**Issue by XinyuCacib** [aneoconsulting/ArmoniK#55]
Environment: local wsl
Version: Armonik 2.1.0

When local WSL restarted, its ip address change.  
So, i change the appsetting.json on client side to configure the new ip address of armonik.
Then i launch the client to submit calcul task. It seems to me that Armonik keeps cached the old ip wsl (which no longer exists) during the connection. 
    
I specify that the client launched the task and the task is well received by the container compute-plane, but after that the execution crashes in armonik . 
 
Root Exception cause : Grpc.Core.RpcException | message : Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: No route to host (172.18.45.87:5001) SocketException: No route to host", DebugException="System.Net.Http.HttpRequestException: No route to host (172.18.45.87:5001) ---> System.Net.Sockets.SocketException (113): No route to host at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken) at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at Grpc.Shared.TelemetryHeaderHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)") Reversed StackTrace : at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) at ArmoniK.Core.gRPC.V1.ClientService.ClientServiceClient.CreateSession(SessionOptions request, CallOptions options) in /src/DevelopmentKit/csharp/Generated/src/obj/Debug/net5.0/ClientServiceGrpc.cs:line 214 at ArmoniK.Core.gRPC.V1.ClientService.ClientServiceClient.CreateSession(SessionOptions request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /src/DevelopmentKit/csharp/Generated/src/obj/Debug/net5.0/ClientServiceGrpc.cs:line 209 at ArmoniK.DevelopmentKit.GridServer.ArmonikDataSynapseClientService.CreateSession(TaskOptions taskOptions) at ArmoniK.DevelopmentKit.GridServer.ServiceAdminWorker..ctor(IConfiguration configuration, TaskOptions taskOptions) at ArmoniK.DevelopmentKit.GridServer.GridWorker.InitializeSessionWorker(String session) at ArmoniK.DevelopmentKit.WorkerApi.Services.ComputerService.Execute(ComputeRequest request, ServerCallContext context) in /src/DevelopmentKit/csharp/WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/Services/ComputerService.cs:line 97

**Comment by ddubuc** [comment]
We move back to simple loadBalancer. We also need to think about workaround for AWS with Elastic IP
