### ISSUE TITLE
Add dashboard for monitoring

### ISSUE THREAD

**Issue by aneojgurhem** [aneoconsulting/ArmoniK#56]
Interesting metrics:

- [x] Cpu 
- [x] Nombre de tâches dans la queue
- [x] Nombre de tâche en processing
- [x] Mémoire
- [x] Disk IOs
- [x] Nombre de tâches terminees
- [ ] Nombre de retry
- [ ] Nombre de pod bien deployes
- [ ] Nombre de pod actifs (au sens de la liveness)
- [ ] Nombre de cœurs utilisés par nos conteneurs
- [ ] Nombre d'instances des conteneurs de controle
- [ ] Métriques de bases de données (nombre de transactions /s, volume des données, etc.

**Comment by lemaitre-aneo** [comment]
Remaining subtasks will be handled in ArmoniK.Gui
