### ISSUE TITLE
Net standard 2.0

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#569]
- [ ] Extensions.Csharp
- [ ] API

**Comment by ngruelaneo** [comment]
- [ ] Certificate management in 2.0

**Comment by aneojgurhem** [comment]
@dbrasseur-aneo what you did with API (include grpc channel factory in ext) right ?
Can we close this ? the remaining modifications of ext for net20 should be done in ext refactoring. @ngruelaneo

**Comment by dbrasseur-aneo** [comment]
Yeah we can close this. More things may be changeable to net 2.0 in ext c#, but it would be on a case by case basis.
