### ISSUE TITLE
fix: use 'like' instead of 'equal' when filter on id

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK#570]
Admin gui 0.7.0

**Is your feature request related to a problem? Please describe.**

I need to seach for a taskid and its retries

**Describe the solution you'd like**

do a like instead of equal in the search field

**Comment by esoubiran-aneo** [comment]
Is the purpose: To have a vision on all the retries of a task?

**Comment by esoubiran-aneo** [comment]
maybe use a * or nothing
