### ISSUE TITLE
[C#] Add Log support for the gridlib

### ISSUE THREAD

**Issue by wkirschenmann** [aneoconsulting/ArmoniK#6]
Gridlib will need to be given a ILogger object to generate its logs.

- [ ] listing de la stack trace (multiple lines)

**Comment by wkirschenmann** [comment]
SymphonyAPI should also provide a IloggerFactory

**Comment by ddubuc** [comment]
Need to enrich log with Error and Exception

**Comment by ddubuc** [comment]
Reference to Issue #67

**Comment by ddubuc** [comment]
- Fixed issue with Exception in version 2.5.2
