### ISSUE TITLE
Integrate AWS CloudWatch

### ISSUE THREAD

**Issue by ddubuc** [aneoconsulting/ArmoniK#60]
Need FluentBit integration #67

**Comment by ddubuc** [comment]
- Select fluent bit config from the Output
- Introduce new variable to select DaemonSet or SideCar

**Comment by lzianekhodja** [comment]
Fluent-bit used to retrieve application logs, user can choose one of these implementations :

- fluent-bit as sidecar in control-plane and compute-plane
- fluent-as daemonset 

Output of logs:

- Seq
- CloudWatch
