### ISSUE TITLE
Create secrets kube for storages' endpoints

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#603]
Create Kubernetes secrets to save:
* MongoDB endpoints
* Redis (Elasticache) endpoints
* ActiveMQ (Amazon MQ) endpoints

Update ArmoniK, Metrics exporter, Partition metrics exporter, partition job and partition cronjob modules.

**Comment by lemaitre-aneo** [comment]
Waiting customer approval.
