### ISSUE TITLE
Update to Node.js actions 16

### ISSUE THREAD

**Issue by jfonseca-aneo** [aneoconsulting/ArmoniK#612]
We see a bunch of warnings suggesting this update when executing the pipeline. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

- [x] ArmoniK https://github.com/aneoconsulting/ArmoniK/pull/637
- [x] Infra https://github.com/aneoconsulting/ArmoniK.Infra/pull/1
- [x] Api https://github.com/aneoconsulting/ArmoniK.Api/pull/73
- [x] Core https://github.com/aneoconsulting/ArmoniK.Core/pull/169
- [x] Extensions.Csharp https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/pull/105
- [x] Samples https://github.com/aneoconsulting/ArmoniK.Samples/pull/23
- [x] GUI https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/274

**Comment by esoubiran-aneo** [comment]
fix https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/274
