### ISSUE TITLE
Investigate if we can feed docker-compose health checks with our own health checks.

### ISSUE THREAD

**Issue by jfonseca-aneo** [aneoconsulting/ArmoniK#623]
On docker compose, if service A depends on service B; it is possible that A waits until B is marked as healthy with the [depends_on](https://docs.docker.com/compose/compose-file/#depends_on) clause. The idea is to investigate if on the
compose health check we can use the health checks already provided by core.  In particular, it will be really useful to be able to use an http test.

**Comment by aneojgurhem** [comment]
We will use Terraform instead of docker-compose and use the health check with Terraform.
