### ISSUE TITLE
Error Connecting to database with NodeJS v17+ in dev environment

### ISSUE THREAD

**Issue by Faust1-2was-Aneo** [aneoconsulting/ArmoniK#695]
In dev environment, while using a local mongodb database (on 127.0.0.1), mongoose is unable to connect to it.

This is because NodeJS, since v17, listen to IPv6 instead of IPv4. It results in mongoose listening `::1` (IPv6) and not `127.0.0.1` for `localhost`.

To resolve it, either set the `MongoDB__Host` to `127.0.0.1` in .env or change the host from `"localhost"` to `"127.0.0.1"` in mongo-client.options.ts

**Comment by esoubiran-aneo** [comment]
Related to https://github.com/aneoconsulting/ArmoniK/issues/672

**Comment by esoubiran-aneo** [comment]
fixed
