### ISSUE TITLE
Integration Armonik in AWS

### ISSUE THREAD

**Issue by ddubuc** [aneoconsulting/ArmoniK#70]
1. Deployment mongoDB as Service in AWS
2. Retrieve Endpoint of MongoDB
3. Adapt Environement variable for Armonik (Onprem, AWS)
4. Integrate S3 Developement in Armonik
5. Integration test (With David)
6. Update Documentation

**Comment by ngruelaneo** [comment]
C'est fait.
David a testé et cela a fonctionné sur GMD mais besoin de confirmation de la part de equity
