### ISSUE TITLE
grpc Exception with TryGetResult

### ISSUE THREAD

**Issue by arnaudcacib** [aneoconsulting/ArmoniK#71]
Problem : TryGetResult called quickly throw a grpc exception
how to reproduce : 
in sample : [repo]\Armonik-v2.3.0\source\ArmoniK.Samples\Samples\SymphonyLike\ArmoniK.Samples.SymphonyClient\Program.cs

    private static byte[] WaitForSubTaskResult(SessionService sessionService, string taskId)
    {
      //System.Threading.Thread.Sleep(5000); //uncomment this and code will not throw exception
      **byte[] tryGetResult = sessionService.TryGetResult(taskId); //add this line to reproduce the bug**
      sessionService.WaitSubtasksCompletion(taskId);
      var taskResult = sessionService.GetResult(taskId);
      var result     = ClientPayload.deserialize(taskResult);
...}

**Comment by ddubuc** [comment]
Fixed
