### ISSUE TITLE
trygetResult return wrong data :

### ISSUE THREAD

**Issue by arnaudcacib** [aneoconsulting/ArmoniK#72]
Problem : TryGetResult return incorrect bytes
in fact it return ?+carriage return+correct bytes
how to reproduce :
in sample : [repo]\Armonik-v2.3.0\source\ArmoniK.Samples\Samples\SymphonyLike\ArmoniK.Samples.SymphonyClient\Program.cs

    private static byte[] WaitForSubTaskResult(SessionService sessionService, string taskId)
    {
      System.Threading.Thread.Sleep(5000);
      byte[] tryGetResult = sessionService.TryGetResult(taskId);
      var tryGetResultStr = Encoding.ASCII.GetString(tryGetResult);
      Console.WriteLine($"tryGetResultstr - size={tryGetResult.Length} string:'{tryGetResultStr}'"); //weird output

      sessionService.WaitSubtasksCompletion(taskId);
      var taskResult = sessionService.GetResult(taskId);
      var getResultStr = Encoding.ASCII.GetString(taskResult);
      Console.WriteLine($"getResultstr - size={getResultStr.Length} string:'{getResultStr}'"); //good output

      var result     = ClientPayload.deserialize(taskResult);
...
  }

tryGetResultstr - size=235 string:'
?eyJJc1Jvb3RUYXNrIjpmYWxzZSwiVHlwZSI6NiwibnVtYmVycyI6bnVsbCwicmVzdWx0IjowLCJTdWJUYXNrSWQiOiJBcm1vbmlrVGFnN2YzNWZhNjUtMWYwZS00ZjIwLWEyZTItYWUzZDAwZDdlZTRiI0FybW9uaWtUYWc5ZmM1ZmYwNi1hZDQ1LTQxMWMtYmU4ZC1hZTNkMDBkN2VlNTMiLCJzbGVlcCI6MH0='
getResultstr - size=232 string:'eyJJc1Jvb3RUYXNrIjpmYWxzZSwiVHlwZSI6NiwibnVtYmVycyI6bnVsbCwicmVzdWx0IjowLCJTdWJUYXNrSWQiOiJBcm1vbmlrVGFnN2YzNWZhNjUtMWYwZS00ZjIwLWEyZTItYWUzZDAwZDdlZTRiI0FybW9uaWtUYWc5ZmM1ZmYwNi1hZDQ1LTQxMWMtYmU4ZC1hZTNkMDBkN2VlNTMiLCJzbGVlcCI6MH0='
[

**Comment by ddubuc** [comment]
Fixed in 2.5.0
