### ISSUE TITLE
ServiceFactory.GetInstance().CreateService Exception in Properties instance

### ISSUE THREAD

**Issue by XinyuCacib** [aneoconsulting/ArmoniK#73]
Problem :  Exception in the instance of Properties when call ServiceFactory.GetInstance().CreateService 
If we instance of Properties  with its constructor 
public Properties(string connectionAddress, int connectionPort, TaskOptions options)

We think that the Properties  instance is wrongly created! 

Api method: public Service CreateService(string serviceType, Properties props)

How  to reproduce: 
var props = new Properties("http://192.168.189.100", 5001, taskOptions);

**Comment by XinyuCacib** [comment]
Hello 

In last version 2.5.1,  we still face to an exception with the parameters  connectionAddress, connectionPort

In fact, the new constructor is declared as 

public Properties(
      IConfiguration configuration,
      TaskOptions options,
      string connectionAddress = null,
      int connectionPort = 0,
      string protocol = null)

Which we tested is like following but it returned an exception 
var props = new Properties(null, taskOptions, "172.18.80.137", 5001);

 Please take a look

**Comment by ddubuc** [comment]
Hi @XinyuCacib,

Could you please provide the exception stacktrace ? Juste to checkif the issue is the same than the previous one

**Comment by XinyuCacib** [comment]
Value cannot be null. (Parameter 'configuration')

In this case,  the configuration in Properties instance is null

**Comment by ddubuc** [comment]
In case you don't want to set AppSettings or Environnement variable. A Properties Object constructor will be created without this argument in the DataSynapse API
