### ISSUE TITLE
Simplify workspace

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK#737]
create libs
- sessions
- [x] feature, used for smart components
- [x] data-access, used for service and api-call
- tasks
- [x] feature, used for smart components
- [x] data-access, used for service and api-call
- results
- [x] feature, used for smart components
- [x] data-access, used for service and api-call
- shared
- [x] ui, used for dump components
- [x] util, used for proto
- [x] feature, used for services

migrate libs
- sessions
- [x] feature, used for smart components
- [x] data-access, used for service and api-call
- tasks
- [x] feature, used for smart components
- [x] data-access, used for service and api-call
- results
- [x] feature, used for smart components
- [x] data-access, used for service and api-call
- shared
- [x] ui, used for dump components
- [x] util, used for proto

Sources
- https://www.youtube.com/watch?v=7SDpTOLeqHE
- https://github.com/joshuamorony/nx-angular-structure
- https://nx.dev/more-concepts/grouping-libraries
- https://nx.dev/more-concepts/library-types

**Comment by Barbapapazes** [comment]
Thanks to this new organisation and nx capacities (caching and affected projects), build time and tests will be faster

**Comment by esoubiran-aneo** [comment]
And we also group by context which simplify code review and organisation

**Comment by esoubiran-aneo** [comment]
Nx graph will also allow us to easily discover and understand repo
