### ISSUE TITLE
RaspberryPi ArmoniK Integration

### ISSUE THREAD

**Issue by ddubuc** [aneoconsulting/ArmoniK#78]
Armonik Installation on the raspbery pi cluster:

- [x] Update Linux system
- [x] Install kube on RaspBerryPi 
- [x]  Preparing network for all nodes
- [x] Running Kube Cluster 
- [x] First deployment on ArmoniK
   - [x] storage
   - [x] monitoring (all but Seq)
   - [x] Seq
   - [x]  control plane
   - [x] compute plane
- [x] .NET build 
- [x] Docker build
- [x] Test armonik job
- [x] Start and validate multiple tasks

**Comment by ddubuc** [comment]
1. Install kube on RaspBerryPi (WIP)
2. Preparing network for all nodes
3. Running Kube Cluster (TODO)
4. First deployment on ArmoniK (TODO)

**Comment by ngruelaneo** [comment]
Mise à jour des systèmes car trop vieux

**Comment by lzianekhodja** [comment]
* K0S: kubernetes installed on the cluster
*.NET build 
* Docker build in progress

**Comment by lemaitre-aneo** [comment]
Using docker as CRI messes the network configuration up. Locally built images can be imported into k0s with the command `k0s ctr images import images.tar`.
