### ISSUE TITLE
Bug Buffering submission

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK#833]
**Describe the bug**
When we do a submission with the buffering submission we have lost the correlation between payload and taskId.
I tested when the MaxTasksPerBuffer is greater than 1 and we have the problem.
To continue the install of 2.10 I set It to 1.

**To Reproduce**
given : 
- We have multiple payloads with unique id in each
when :
- We submit these payloads with the buffering submission
Then :
- We receive a task.Id for each payload
- in the grid we have task.Id=1 with payload.Id=1
- in the client we have task.Id=1 with payload.Id=:x:2:x:

**Expected behavior**
given : 
- We have multiple payloads with unique id in each
when :
- We submit these payloads with the buffering submission
Then :
- We receive a task.Id for each payload
- in the grid we have task.Id=1 with payload.Id=1
- in the client we have task.Id=1 with payload.Id=:heavy_check_mark:1:heavy_check_mark:

**Infra**
- Target (Local, AWS, Docker compose, etc..) : AWS
- Queue (Activemq managed or not) : Activemq managed 
- DataBase (MongoDB) : MongoDB
- Cache (Redis managed or not) : Redis managed
- Infra Version : ?
- Core Images and Version (if known) : 0.8.2
- Worker Image and Version (if known) : 0.8.1

**Comment by aneojgurhem** [comment]
Hello @landdragon,
The issue is great but can you provide a little bit more information on your use case ? I suspect that you use one of our API to submit your tasks but can you tell us which one and which functions ? Do you have some code snippets that could help us reproduce the issue on our end ?
Those new informations would greatly help us to investigate and eventually solve your issue faster.
Thank you !

**Comment by landdragon** [comment]
I use the unified API and we use  [SubmitAsync](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/72c431498a657a73cc9fd99e89c1e852710b8c46/Client/src/Unified/Services/Submitter/Service.cs#L343).

I didn't finish the test to reproduce it.

**Comment by landdragon** [comment]
[test.zip](https://github.com/aneoconsulting/ArmoniK/files/10459591/test.zip)
my test case to reproduce it

**Comment by ddubuc** [comment]
Thanks. We will test with our potential fix today
