### ISSUE TITLE
MongoDB full when the number of tasks exceeds 500

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#88]
System.AggregateException: One or more errors occurred. (The wait queue for acquiring a connection to server 10.43.207.7:27017 is full.) ---> MongoDB.Driver.MongoWaitQueueFullException: The wait queue for acquiring a connection to server 10.43.207.7:27017 is full.

**Comment by ddubuc** [comment]
Fix in 2.5.2
