### ISSUE TITLE
when redis adapter fails there is no retry

### ISSUE THREAD

**Issue by alouvion-aneo** [aneoconsulting/ArmoniK#880]
**Describe the bug**
data adapter redis may fails if too much requests at the same time
5 jobs with 1 000 000 bytes of data => RedisTimeOutException
if I send 10 000 tasks some may fails and in admin tool I will not see 10 000 tasks but maybe only 853
todo : check similar behaviour in S3  

**To Reproduce**
install armonik
launch stresstest for exemple with those parametes :   "--nbTask 100000  --nbInputBytes 1000000 --nbOutputBytes 1000000  --workLoadTimeInMs 0",
for exemple 5 times in // at the same time
=> check logs in seq, you will find RedisTimeOutException
=> chek in adminTool you will not see : 10 000 tasks 5x times
maybe you will see something like that : 
session id                                                                  |  task count
da801226-23da-4c7a-a6d7-961558f9550e              |    2  327
da801226-23da-4c7a-a6d7-936578f9550f               |  10 000
da801226-23da-4c7a-a6d7-961712f9550g              |       823
da801226-23da-4c7a-a6d7-961558f9550h              |    1 328
da801226-23da-4c7a-a6d7-961558f9550i               |    3 457

**Expected behavior**
in admintool you must see : 
session id                                                                  |  task count
da801226-23da-4c7a-a6d7-961558f9550e              |  10 000
da801226-23da-4c7a-a6d7-936578f9550f               |  10 000
da801226-23da-4c7a-a6d7-961712f9550g              |  10 000
da801226-23da-4c7a-a6d7-961558f9550h              |  10 000
da801226-23da-4c7a-a6d7-961558f9550i               |  10 000

**Comment by lemaitre-aneo** [comment]
A way to mitigate it would be to disable parallel uploads of the objects. That way, you would only have a single connection per agent.
