### ISSUE TITLE
rename ITaskSubmitterWorkerServiceConfiguration 

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK#881]
**Describe the bug**

This interface should not be named [ITaskSubmitterWorkerServiceConfiguration](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/3178612e07b0cf9a86a662746e677dc4c665a5d1/Worker/src/Unified/ITaskSubmitterWorkerServiceConfiguration.cs#L29) because it have nothing associate to Submission.
And It should not be Internal.

**Expected behavior**
the class may be name IServiceConfiguration or something else and put It public

**Additional context**
already talk with @ddubuc 
cc: @alouvion-aneo

**Comment by ngruelaneo** [comment]
Done with: https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/pull/136
