### ISSUE TITLE
problem of visibility inside TaskSubmitterWorkerService

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK#882]
**Describe the bug**
inside [TaskSubmitterWorkerService](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/3178612e07b0cf9a86a662746e677dc4c665a5d1/Worker/src/Unified/TaskSubmitterWorkerService.cs#L54) the [SessionId](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/3178612e07b0cf9a86a662746e677dc4c665a5d1/Worker/src/Unified/TaskSubmitterWorkerService.cs#L86) property is never set and the [SessionService](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/3178612e07b0cf9a86a662746e677dc4c665a5d1/Worker/src/Unified/TaskSubmitterWorkerService.cs#L91) is internal so I can't have access to the Session Id.

**Additional context**
already talk with @ddubuc
cc: @alouvion-aneo

**Comment by ngruelaneo** [comment]
Done in: https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/pull/136
