### ISSUE TITLE
in redis adapter : do not use manual multipart files

### ISSUE THREAD

**Issue by alouvion-aneo** [aneoconsulting/ArmoniK#884]

**Comment by lemaitre-aneo** [comment]
This was a lead to simplify the Redis Adapter, but there is nothing in the Redis library that would allow to upload or download with streams, so this might be a dead end.

It might be possible to use append for uploads, and range get for downloads, but I'm not convinced it is worth the effort.

**Comment by aneojgurhem** [comment]
There are streams in Redis, but I am not really sure if it fits for our use case : https://redis.io/docs/data-types/streams/

**Comment by lemaitre-aneo** [comment]
> There are streams in Redis, but I am not really sure if it fits for our use case : https://redis.io/docs/data-types/streams/

I am still unsure if this is a way to have multi-part object in the form of a time series, or if this is a way to synchronize multiple agents together like a queue.

**Comment by aneojgurhem** [comment]
That's my concern too
