### ISSUE TITLE
Add limit for retention in seq deployment

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#940]
First suggestion:

```bash
seq config retention -k default -s “*” -a 48
```
According to @ddubuc that's not working and the advice is to instead use:

```bash
curl -X POST http://ddu-srv-wsl:5000/seq/api/retentionpolicies -H 'Content-Type: application/json' -d '{"RetentionTime":"2.00:00:00","RemovedSignalExpression":null}'
```

**Comment by lemaitre-aneo** [comment]
This could be done in post Startup?

**Comment by ddiakiteaneo** [comment]
Add retention in seq using cron jobs and seqcli: 
- [ x ] Local all-in-one deployment
- [ x ] Local split deployment
- [ x ] AWS all-in-one deployment
- [ x ] AWS split deployment

**Comment by ddiakiteaneo** [comment]
Add retention in seq using cron jobs and seqcli: 
- [x] Local all-in-one deployment
- [x] Local split deployment
- [x] AWS all-in-one deployment
- [x] AWS split deployment
