### ISSUE TITLE
Complete terraform's modules to deploy Core

### ISSUE THREAD

**Issue by jfonseca-aneo** [aneoconsulting/ArmoniK#943]
There are still some terraform modules  to be added in Core in order to safely deprecate the docker-compose based deployment: In particular, we need to add modules to deploy the following images: 

- [ ] grafana/tempo
- [x] grafana/grafana
- [x] prom/prometheus

The configuration that each module defines for the image its responsible for, should mirror that of the corresponding [docker-compose files](https://github.com/aneoconsulting/ArmoniK.Core/tree/main/docker-compose)

**Comment by melflitty** [comment]
We will not deploy grafana/tempo.
