### ISSUE TITLE
Add NuGet AWSSDK.SecutityToken in control-plane, scheduling-agent and worker docker images

### ISSUE THREAD

**Issue by lzianekhodja** [aneoconsulting/ArmoniK#964]
The AWS Security Token Service (AWS STS) enables you to provide trusted users with temporary credentials that provide controlled access to your AWS resources.

The NuGet AWSSDK.SecutityToken is needed in ArmoniK's docker images when least privileges are assigned to pods in the form of AWS roles. 

- [x] api
- [x] core
- [x] Ext.C#
- [ ] Samples : pb buildX => https://github.com/aneoconsulting/ArmoniK.Samples/actions/runs/4637224957/jobs/8257907064
- [x] infra

**Comment by ngruelaneo** [comment]
The CI for the sample does seems to not work properly but it is only for the demo images which are not used. 
This CI will be updated and the problem will disapear. 
We can close this issue.
