### ISSUE TITLE
Expose more inforamtion about the task waitting result

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK#966]
**Is your feature request related to a problem? Please describe.**
I have a client who is waitting a result without end

**Describe the solution you'd like**
I need more information to detect where is the true problem.
can you expose (change to public) [this property](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/8e4ec487c1023799c4211c2bc0f484611007ede0/Client/src/Unified/Services/Common/AbstractClientService.cs#L33)
or create accessor public to have access to the count (number of task waitting result) and a list of task id (the key).

**Comment by dbrasseur-aneo** [comment]
@landdragon Thank you for your report,
Please, can you provide us with more informations regarding your problem :  
- Version of Extensions.Csharp client and worker
- Version of ArmoniK
- Is the issue related to #901 (This issue as fixed as part of the 2.12.0 release) ?
- Can you provide a way to reproduce the problem ?
- Does this issue appear consistently or randomly ?
- Does this issue appear following a network problem ? 

It would be beneficial for the project if we can fix an underlying issue with Extensions.Csharp using your answers.

Best regards

**Comment by landdragon** [comment]
hello,

this ticket is related to this one https://github.com/aneoconsulting/ArmoniK/issues/977 .
**But here I just ask to let me have more information** to know the number of result task remaining to get from the Grid and if I have a diff between the number I have on my side and yours I will print the taskid (on your side it is the key of the dictionary).


- Version of Extensions.Csharp client and worker
 0.8.2
- Version of ArmoniK
2.10.3
- Is the issue related to https://github.com/aneoconsulting/ArmoniK/issues/901 (This issue as fixed as part of the 2.12.0 release) ?
no
- Can you provide a way to reproduce the problem ?
no it is too complex to reproduce it
- Does this issue appear consistently or randomly ?
randomly
- Does this issue appear following a network problem ?
I don't think

**Comment by dbrasseur-aneo** [comment]
@landdragon Would this PR https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/pull/150 fulfill your query ?

**Comment by landdragon** [comment]
très bien merci :)
