### ISSUE TITLE
problem during sending buffer

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK#977]
**Describe the bug**
I have a client who is stuck into the send of all task.
I think the problem is inside the send of buffer.

**To Reproduce**
It is not easy to reproduce

**Expected behavior**
Not be stuck :)

**Infra**
- Target (Local, AWS, Docker compose, etc..) : AWS
- Queue (Activemq managed or not) : Amazon MQ
- DataBase (MongoDB) : MongoDB
- Cache (Redis managed or not) : elasticache redis
- Infra Version : 2.10.3
- Core Images and Version (if known) : 0.8.2
- Worker Image and Version (if known) : 0.8.2

I already explain the problem to @ddubuc

**Comment by ngruelaneo** [comment]
Thank you very much for the report, unfortunately @ddubuc is not available today so can you describe with more details in *this issue* the problem so the team can try to solve it.

**Comment by landdragon** [comment]
hello,

[here](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/ad6747b45d9a4e600788f2d3ccfb6c840db4a99d/Client/src/Unified/Services/Submitter/Service.cs#L132) we have a method used inside a thread and in case of throw the thread is kill and we are stuck.
we continue to send message inside the [SubmitAsync](https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/ad6747b45d9a4e600788f2d3ccfb6c840db4a99d/Client/src/Unified/Services/Submitter/Service.cs#L351) and we await the send to the grid but the thread who send to the grid is off.

**Comment by landdragon** [comment]
and so if it throw I will need a log and a managment of error like a continue, restart  or crash the application

**Comment by dbrasseur-aneo** [comment]
@landdragon Can you provide a way to reproduce the issue ? It would be easier for us.

**Comment by ddubuc** [comment]
Need to fix forward Issue

**Comment by ddubuc** [comment]
@landdragon : 
To review the fix in 0.10.1
https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/pull/158

To compare with 0.8.2 (2.10.2)
https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/compare/0.8.2...ddu/backPort_BufferException

**Comment by landdragon** [comment]
Just the re throw of the exception you put `throw e;` it is better to encapsulate inside an new exception otherwise we will lost the stack trace

**Comment by ddubuc** [comment]
@landdragon Are you taking about this line ? 
https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/7c5c67329538f17adc31fbc7c5a10fa4fe5e6fdb/Client/src/Common/Submitter/RequestTaskMap.cs#L66

**Comment by landdragon** [comment]
yes

**Comment by ddubuc** [comment]
@landdragon So the idea for you is as below ? 

```csharp 
  /// <summary>
  ///   Get the correct taskId based on the SubmitId
  /// </summary>
  /// <param name="submitId">The submit Id push during the submission</param>
  /// <returns>the async taskId</returns>
  public async Task<string> GetResponseAsync(Guid submitId)
  {
    while (!dictionary_.ContainsKey(submitId))
    {
      await Task.Delay(WaitTime);
    }

    return dictionary_[submitId]
      .IfRight(e => throw new ClientApiException("Submission failure", e));
  }
```

**Comment by landdragon** [comment]
nice :)
