### ISSUE TITLE
Change timespan to Milliseconds

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK#984]
**Is your feature request related to a problem? Please describe.**
When i use Kibana to create dashboad about metrics I need milliseconds insted of timespan.

**Describe the solution you'd like**
[Here](https://github.com/aneoconsulting/ArmoniK.Api/blob/5d7846f30776cc471ce17c9d329f91832ca986c4/packages/csharp/ArmoniK.Api.Common/Utils/LoggerExt.cs#L142) I prefer to use `stopWatch.ElapsedMilliseconds`

@ddubuc  as you ask me, I gived you the exact code I need :)

**Comment by dbrasseur-aneo** [comment]
@landdragon Would this fix suit you ? https://github.com/aneoconsulting/ArmoniK.Api/pull/225/files
